[package]
name = "registry-client"
version = "0.1.0"
authors = ["Pengfei Zhang <zpfalpc23@gmail.com>"]
edition = "2018"

[dependencies]
curl = "0.4"
failure = "0.1.1"
http = "0.1"
serde = { version = "1.0", features = ['derive'] }
serde_derive = "1.0"
serde_json = "1.0"
url = "1.0"
